apiVersion: apps/v1
kind: Deployment
metadata:
  name: MAKEFILE_SERVICE_NAME-postgres
spec:
  selector:
    matchLabels:
      app: MAKEFILE_SERVICE_NAME-postgres
  template:
    metadata:
      labels:
        app: MAKEFILE_SERVICE_NAME-postgres
    spec:
      containers:
      - name: MAKEFILE_SERVICE_NAME-postgres
        image: postgres:14-alpine
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".5"
            memory: "1G"
          limits:
            cpu: "3"
            memory: "3G"
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: pods-admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-MAKEFILE_SERVICE_NAME-secrets
              key: postgres-password
        ports:
        - name: postgres
          containerPort: 5432
          
    # Should be a PVC mount here.