entryPoints:
  web:
   address: ":80"
  dash:
   address: ":8080"

http:
  middlewares:
    path-strip-v3:
      stripPrefix:
        prefixes:
         - "/v3"

  routers:
    pods-service:
      rule: "PathPrefix(`/v3/pods`)"
      middlewares:
       - "path-strip-v3"
      service: pods-service

    api:
      rule: "PathPrefix(`/api`)"
      service: api@internal

  services:
    pods-service:
      loadBalancer:
        servers:
         - url: http://pods-api:8000
