
# Whoami test image for testing tests.
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: default
  labels:
    app: traefik-app
    name: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik-app
      task: whoami
  template:
    metadata:
      labels:
        app: traefik-app
        task: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: default

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: traefik-app
    task: whoami



#### SERVICES
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-service
spec:
  type: NodePort
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
    - protocol: TCP
      port: 8080
      name: admin
      targetPort: 8080
    - protocol: TCP
      port: 8000
      name: tcpep
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  type: NodePort
  selector:
    app: envoy
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80

